# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

doxa_binary <- function(x, height, width, type, opts) {
    .Call('_image_binarization_doxa_binary', PACKAGE = 'image.binarization', x, height, width, type, opts)
}

